def main():
	print("Hello world!")
	test_simobject()

def test_simobject():
	import simobject as so

	obj = so.SimObject(5, 4)
	print("\nid")
	print(obj.get_id())
	print("\neval")
	print(obj.get_evaluated())
	obj.set_evaluated(True)
	print(obj.get_evaluated())
	print("\ninput locs")
	print(obj.get_input_locations())
	obj.set_input_locations([(0, 1), (9, 8)])
	print(obj.get_input_locations())
	print("\ninput vals")
	print(obj.get_input_values())
	obj.set_input_values([False, True])
	print(obj.get_input_values())
	print("\noutput vals")
	print(obj.get_output_values())
	obj.set_output_values([True, False])
	print(obj.get_output_values())


	obj2 = so.SimObject(6, 2)
	# set_input_location()
	print("\nset_input_location")
	print(obj2.get_input_locations())
	obj2.set_input_location(2, (5, 5))
	print(obj2.get_input_locations())
	# set_input_value()
	print("\nset_input_value")
	print(obj2.get_input_values())
	obj2.set_input_value(3, True)
	print(obj2.get_input_values())
	# add_input()
	print("\nadd_input")
	print(obj2.get_input_locations())
	obj2.add_input(4)
	print(obj2.get_input_locations())
	# add_output()
	print("\nadd_output")
	print(obj2.get_output_values())
	obj2.add_output(2)
	print(obj2.get_output_values())
	# connect_input()
	print("\nconnect_input")
	print(obj2.get_input_locations())
	obj2.connect_input(0, 10, 5)
	print(obj2.get_input_locations())
	# get_num_inputs()
	print("\nget_num_inputs")
	print(obj2.get_num_inputs())
	# get_num_outputs()
	print("\nget_num_outputs")
	print(obj2.get_num_outputs())

if __name__ == "__main__":
	main()